/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 14 19:36:53 GMT 2026
 */

package org.apache.zookeeper.server.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedInputStream;
import java.io.FilterInputStream;
import java.io.PipedInputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import java.util.Map;
import org.apache.zookeeper.server.admin.CommandResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResponse_ESTest extends CommandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      Object object0 = new Object();
      commandResponse0.put("", object0);
      commandResponse0.put("", (Object) null);
      assertEquals("", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("FESIC]q(p,I");
      int int0 = commandResponse0.getStatusCode();
      assertEquals(200, int0);
      assertEquals("FESIC]q(p,I", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Enumeration<FilterInputStream> enumeration0 = (Enumeration<FilterInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      CommandResponse commandResponse0 = new CommandResponse("", "", (-2633), sequenceInputStream0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals("", commandResponse0.getCommand());
      assertEquals((-2633), int0);
      assertEquals("", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("org.apache.zookeeper.server.admin.CommandResponse", "S:o9^xkVDbx>]y4i", 0);
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      BufferedInputStream bufferedInputStream0 = new BufferedInputStream(pipedInputStream0);
      commandResponse0.setInputStream(bufferedInputStream0);
      commandResponse0.getInputStream();
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("S:o9^xkVDbx>]y4i", commandResponse0.getError());
      assertEquals("org.apache.zookeeper.server.admin.CommandResponse", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("org.apache.zookeeper.server.admin.CommandResponse", "S:o9^xkVDbx>]y4i", 0);
      commandResponse0.addHeader("org.apache.zookeeper.server.admin.CommandResponse", "");
      commandResponse0.getHeaders();
      assertEquals("S:o9^xkVDbx>]y4i", commandResponse0.getError());
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("org.apache.zookeeper.server.admin.CommandResponse", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("org.apache.zookeeper.server.admin.CommandResponse", "S:o9^xkVDbx>]y4i", 0);
      String string0 = commandResponse0.getError();
      assertEquals("S:o9^xkVDbx>]y4i", string0);
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("org.apache.zookeeper.server.admin.CommandResponse", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Enumeration<FilterInputStream> enumeration0 = (Enumeration<FilterInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      CommandResponse commandResponse0 = new CommandResponse("", "", (-2633), sequenceInputStream0);
      String string0 = commandResponse0.getError();
      assertEquals("", commandResponse0.getCommand());
      assertEquals("", string0);
      assertEquals((-2633), commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 0);
      String string0 = commandResponse0.getCommand();
      assertEquals(0, commandResponse0.getStatusCode());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      String string0 = commandResponse0.getCommand();
      assertEquals("", string0);
      assertNotNull(string0);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("%");
      // Undeclared exception!
      try { 
        commandResponse0.putAll((Map<String, ?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 0);
      String string0 = commandResponse0.getError();
      assertEquals(0, commandResponse0.getStatusCode());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 0);
      Map<String, Object> map0 = commandResponse0.toMap();
      commandResponse0.putAll(map0);
      assertEquals(0, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 0);
      commandResponse0.getInputStream();
      assertEquals(0, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("!hd/");
      commandResponse0.setStatusCode((-415));
      assertEquals((-415), commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("gVY):");
      String string0 = commandResponse0.getCommand();
      assertEquals("gVY):", string0);
      assertEquals(200, commandResponse0.getStatusCode());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.getHeaders();
      assertEquals("", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }
}
