/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 13 17:13:51 GMT 2026
 */

package org.apache.zookeeper.test.evosuite.c2.commandresponse;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import org.apache.zookeeper.server.admin.CommandResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResponse_ESTest extends CommandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse(" C1e0z9xqa7@", " C1e0z9xqa7@", 1);
      commandResponse0.addHeader(" C1e0z9xqa7@", "bN>l6KcOU&M+Qr$C");
      assertEquals(1, commandResponse0.getStatusCode());
      assertEquals(" C1e0z9xqa7@", commandResponse0.getCommand());
      assertEquals(" C1e0z9xqa7@", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, "r1", (-1), (InputStream) null);
      commandResponse0.put((String) null, "error");
      byte[] byteArray0 = new byte[9];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      commandResponse0.put((String) null, byteArrayInputStream0);
      assertEquals((-1), commandResponse0.getStatusCode());
      assertEquals("r1", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse(" C1e0z9xqa7@", " C1e0z9xqa7@", 1);
      assertEquals(1, commandResponse0.getStatusCode());
      
      commandResponse0.setStatusCode(0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 0);
      assertEquals(0, commandResponse0.getStatusCode());
      
      commandResponse0.setStatusCode((-1));
      int int0 = commandResponse0.getStatusCode();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse(" C1e0z9xqa7@", " C1e0z9xqa7@", 1);
      Enumeration<ByteArrayInputStream> enumeration0 = (Enumeration<ByteArrayInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      BufferedInputStream bufferedInputStream0 = new BufferedInputStream(sequenceInputStream0, 1);
      commandResponse0.setInputStream(bufferedInputStream0);
      commandResponse0.getInputStream();
      assertEquals(1, commandResponse0.getStatusCode());
      assertEquals(" C1e0z9xqa7@", commandResponse0.getError());
      assertEquals(" C1e0z9xqa7@", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      String string0 = commandResponse0.getError();
      assertEquals("", commandResponse0.getCommand());
      assertNull(string0);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("d3Dk53;7_\"", "", 0);
      String string0 = commandResponse0.getError();
      assertEquals("d3Dk53;7_\"", commandResponse0.getCommand());
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 1844);
      String string0 = commandResponse0.getCommand();
      assertNull(string0);
      assertEquals(1844, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse(" C1e0z9xqa7@", " C1e0z9xqa7@", 1);
      String string0 = commandResponse0.getCommand();
      assertEquals(" C1e0z9xqa7@", commandResponse0.getError());
      assertEquals(" C1e0z9xqa7@", string0);
      assertEquals(1, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      // Undeclared exception!
      try { 
        commandResponse0.putAll((Map<String, ?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse(" C1e0z9xqa7@", " C1e0z9xqa7@", 1);
      String string0 = commandResponse0.getError();
      assertEquals(1, commandResponse0.getStatusCode());
      assertEquals(" C1e0z9xqa7@", string0);
      assertEquals(" C1e0z9xqa7@", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse(" C1e0z9xqa7@", " C1e0z9xqa7@", 1);
      commandResponse0.addHeader(" C1e0z9xqa7@", " C1e0z9xqa7@");
      commandResponse0.getHeaders();
      assertEquals(1, commandResponse0.getStatusCode());
      assertEquals(" C1e0z9xqa7@", commandResponse0.getError());
      assertEquals(" C1e0z9xqa7@", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse(" C1e0z9xqa7@", " C1e0z9xqa7@", 1);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(" C1e0z9xqa7@", commandResponse0.getCommand());
      assertEquals(1, int0);
      assertEquals(" C1e0z9xqa7@", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.getHeaders();
      assertEquals("", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      HashMap<String, ByteArrayInputStream> hashMap0 = new HashMap<String, ByteArrayInputStream>();
      commandResponse0.putAll(hashMap0);
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("q{=Ga'}K!cn|!I");
      commandResponse0.toMap();
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("q{=Ga'}K!cn|!I", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("iE +9,o=jOZf");
      commandResponse0.getInputStream();
      assertEquals("iE +9,o=jOZf", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      String string0 = commandResponse0.getCommand();
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("", string0);
      assertNotNull(string0);
  }
}
