/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 13 17:52:02 GMT 2026
 */

package org.apache.zookeeper.test.evosuite.c3.commandresponse;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.InputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import java.util.Map;
import org.apache.zookeeper.server.admin.CommandResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResponse_ESTest extends CommandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse(".-!mXI", "5JR1/[", 0, (InputStream) null);
      assertEquals(".-!mXI", commandResponse0.getCommand());
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("5JR1/[", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("g3aB(*-GYr*");
      Map<String, String> map0 = commandResponse0.getHeaders();
      commandResponse0.addHeader("", "g3aB(*-GYr*");
      commandResponse0.putAll(map0);
      Object object0 = commandResponse0.put("", "");
      assertNotNull(object0);
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("g3aB(*-GYr*", object0);
      assertEquals("g3aB(*-GYr*", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.setStatusCode(0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "d::N", (-1));
      int int0 = commandResponse0.getStatusCode();
      assertEquals("d::N", commandResponse0.getError());
      assertEquals("", commandResponse0.getCommand());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      Enumeration<SequenceInputStream> enumeration0 = (Enumeration<SequenceInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      commandResponse0.setInputStream(sequenceInputStream0);
      commandResponse0.getInputStream();
      assertEquals("", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("A^'(H/2IEtE^:KS%", "A^'(H/2IEtE^:KS%", 0);
      String string0 = commandResponse0.getError();
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("A^'(H/2IEtE^:KS%", commandResponse0.getCommand());
      assertEquals("A^'(H/2IEtE^:KS%", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("beIZQ90+9*`6))w", "", 0);
      String string0 = commandResponse0.getError();
      assertEquals("beIZQ90+9*`6))w", commandResponse0.getCommand());
      assertEquals("", string0);
      assertEquals(0, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("A?");
      String string0 = commandResponse0.getCommand();
      assertEquals(200, commandResponse0.getStatusCode());
      assertNotNull(string0);
      assertEquals("A?", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      String string0 = commandResponse0.getCommand();
      assertEquals("", string0);
      assertNotNull(string0);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      // Undeclared exception!
      try { 
        commandResponse0.putAll((Map<String, ?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      String string0 = commandResponse0.getError();
      assertEquals("", commandResponse0.getCommand());
      assertNull(string0);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "d::N", (-1));
      commandResponse0.put("U83DsPNsIyL32d\"`i", "d::N");
      assertEquals("", commandResponse0.getCommand());
      assertEquals((-1), commandResponse0.getStatusCode());
      assertEquals("d::N", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "d::N", (-1));
      commandResponse0.addHeader("d::N", "d::N");
      commandResponse0.getHeaders();
      assertEquals("d::N", commandResponse0.getError());
      assertEquals((-1), commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      int int0 = commandResponse0.getStatusCode();
      assertEquals(200, int0);
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("~BM7&?Ry<rnon.p@uX");
      commandResponse0.toMap();
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("~BM7&?Ry<rnon.p@uX", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("~BM7&?Ry<rnon.p@uX");
      commandResponse0.getInputStream();
      assertEquals("~BM7&?Ry<rnon.p@uX", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      String string0 = commandResponse0.getCommand();
      assertEquals(200, commandResponse0.getStatusCode());
      assertNull(string0);
  }
}
