/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 13 16:59:10 GMT 2026
 */

package org.apache.zookeeper.test.evosuite.c1.keeperexception;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import org.apache.zookeeper.KeeperException;
import org.apache.zookeeper.OpResult;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class KeeperException_ESTest extends KeeperException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      KeeperException.InvalidACLException keeperException_InvalidACLException0 = new KeeperException.InvalidACLException();
      keeperException_InvalidACLException0.setCode((-121));
      assertEquals(KeeperException.Code.NOWATCHER, keeperException_InvalidACLException0.code());
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      KeeperException.BadVersionException keeperException_BadVersionException0 = new KeeperException.BadVersionException("");
      String string0 = keeperException_BadVersionException0.getPath();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      KeeperException keeperException0 = KeeperException.create((-6), "bj# zTEhy");
      assertEquals("bj# zTEhy", keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.getCodeMessage((KeeperException.Code) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.create((KeeperException.Code) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.get((-120));
      assertEquals(KeeperException.Code.EPHEMERALONLOCALSESSION, keeperException_Code0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.Code.get(4);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The current client version cannot lookup this code:4
         //
         verifyException("org.apache.zookeeper.KeeperException$Code", e);
      }
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONEXPIRED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.UNKNOWNSESSION;
      // Undeclared exception!
      try { 
        KeeperException.create(keeperException_Code0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid exception code:-12
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      KeeperException.NoWatcherException keeperException_NoWatcherException0 = new KeeperException.NoWatcherException();
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      KeeperException.NotEmptyException keeperException_NotEmptyException0 = new KeeperException.NotEmptyException();
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      KeeperException.ThrottledOpException keeperException_ThrottledOpException0 = new KeeperException.ThrottledOpException();
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      KeeperException.APIErrorException keeperException_APIErrorException0 = new KeeperException.APIErrorException();
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      KeeperException.UnimplementedException keeperException_UnimplementedException0 = new KeeperException.UnimplementedException();
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      KeeperException.NotReadOnlyException keeperException_NotReadOnlyException0 = new KeeperException.NotReadOnlyException();
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      KeeperException.BadArgumentsException keeperException_BadArgumentsException0 = new KeeperException.BadArgumentsException();
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      KeeperException.ConnectionLossException keeperException_ConnectionLossException0 = new KeeperException.ConnectionLossException();
      String string0 = keeperException_ConnectionLossException0.getPath();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      KeeperException.NewConfigNoQuorum keeperException_NewConfigNoQuorum0 = new KeeperException.NewConfigNoQuorum();
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      KeeperException.SessionClosedRequireAuthException keeperException_SessionClosedRequireAuthException0 = new KeeperException.SessionClosedRequireAuthException();
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      KeeperException.NodeExistsException keeperException_NodeExistsException0 = new KeeperException.NodeExistsException();
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      KeeperException.DataInconsistencyException keeperException_DataInconsistencyException0 = new KeeperException.DataInconsistencyException();
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      KeeperException.InvalidCallbackException keeperException_InvalidCallbackException0 = new KeeperException.InvalidCallbackException();
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      KeeperException.OperationTimeoutException keeperException_OperationTimeoutException0 = new KeeperException.OperationTimeoutException();
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      KeeperException.NoNodeException keeperException_NoNodeException0 = new KeeperException.NoNodeException();
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      KeeperException.NoAuthException keeperException_NoAuthException0 = new KeeperException.NoAuthException();
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      KeeperException.SessionExpiredException keeperException_SessionExpiredException0 = new KeeperException.SessionExpiredException();
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      KeeperException.EphemeralOnLocalSessionException keeperException_EphemeralOnLocalSessionException0 = new KeeperException.EphemeralOnLocalSessionException();
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      KeeperException.ReconfigDisabledException keeperException_ReconfigDisabledException0 = new KeeperException.ReconfigDisabledException();
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      KeeperException.RuntimeInconsistencyException keeperException_RuntimeInconsistencyException0 = new KeeperException.RuntimeInconsistencyException();
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      KeeperException.SessionMovedException keeperException_SessionMovedException0 = new KeeperException.SessionMovedException();
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      KeeperException.RequestTimeoutException keeperException_RequestTimeoutException0 = new KeeperException.RequestTimeoutException();
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      KeeperException.BadVersionException keeperException_BadVersionException0 = new KeeperException.BadVersionException("w,{9");
      List<OpResult> list0 = keeperException_BadVersionException0.getResults();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      KeeperException.NoChildrenForEphemeralsException keeperException_NoChildrenForEphemeralsException0 = new KeeperException.NoChildrenForEphemeralsException("");
      String string0 = keeperException_NoChildrenForEphemeralsException0.getMessage();
      assertEquals("KeeperErrorCode = NoChildrenForEphemerals", string0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.THROTTLEDOP;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Op throttled due to high load", string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONCLOSEDREQUIRESASLAUTH;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Session closed because client failed to authenticate", string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.REQUESTTIMEOUT;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Unknown error REQUESTTIMEOUT", string0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.EPHEMERALONLOCALSESSION;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Ephemeral node on local session", string0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOTREADONLY;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Not a read-only call", string0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONMOVED;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Session moved", string0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.AUTHFAILED;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("AuthFailed", string0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      KeeperException.InvalidACLException keeperException_InvalidACLException0 = new KeeperException.InvalidACLException();
      String string0 = keeperException_InvalidACLException0.getMessage();
      assertEquals("KeeperErrorCode = InvalidACL", string0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.INVALIDCALLBACK;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Invalid callback", string0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONEXPIRED;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Session expired", string0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOTEMPTY;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Directory not empty", string0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NODEEXISTS;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("NodeExists", string0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.BADVERSION;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("BadVersion", string0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOAUTH;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("NoAuth", string0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NONODE;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("NoNode", string0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.APIERROR;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("APIError", string0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.UNKNOWNSESSION;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Unknown error UNKNOWNSESSION", string0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NEWCONFIGNOQUORUM;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("NewConfigNoQuorum", string0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.BADARGUMENTS;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("BadArguments", string0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.OPERATIONTIMEOUT;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("OperationTimeout", string0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      KeeperException.MarshallingErrorException keeperException_MarshallingErrorException0 = new KeeperException.MarshallingErrorException();
      String string0 = keeperException_MarshallingErrorException0.getMessage();
      assertEquals("KeeperErrorCode = MarshallingError", string0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.CONNECTIONLOSS;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("ConnectionLoss", string0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.DATAINCONSISTENCY;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("DataInconsistency", string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.RUNTIMEINCONSISTENCY;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("RuntimeInconsistency", string0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      KeeperException.SystemErrorException keeperException_SystemErrorException0 = new KeeperException.SystemErrorException();
      String string0 = keeperException_SystemErrorException0.getMessage();
      assertEquals("KeeperErrorCode = SystemError", string0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.OK;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("ok", string0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      KeeperException keeperException0 = KeeperException.create((-101));
      assertEquals((-101), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.QUOTAEXCEEDED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-125), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.AUTHFAILED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOCHILDRENFOREPHEMERALS;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.BADVERSION;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.BADVERSION, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.UNKNOWNSESSION;
      // Undeclared exception!
      try { 
        KeeperException.create(keeperException_Code0, "org.apache.zookeeper.OpResult$DeleteResult");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid exception code:-12
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.RECONFIGINPROGRESS;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-14), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.MARSHALLINGERROR;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.OK;
      // Undeclared exception!
      try { 
        KeeperException.create(keeperException_Code0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid exception code:0
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.OPERATIONTIMEOUT;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.OPERATIONTIMEOUT, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      KeeperException.BadVersionException keeperException_BadVersionException0 = new KeeperException.BadVersionException();
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONMOVED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      KeeperException.NoChildrenForEphemeralsException keeperException_NoChildrenForEphemeralsException0 = new KeeperException.NoChildrenForEphemeralsException("j");
      String string0 = keeperException_NoChildrenForEphemeralsException0.getMessage();
      assertEquals("KeeperErrorCode = NoChildrenForEphemerals for j", string0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      KeeperException.ReconfigInProgress keeperException_ReconfigInProgress0 = new KeeperException.ReconfigInProgress();
      String string0 = keeperException_ReconfigInProgress0.getMessage();
      assertEquals("KeeperErrorCode = ReconfigInProgress", string0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.INVALIDCALLBACK;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.INVALIDCALLBACK, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.EPHEMERALONLOCALSESSION;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.EPHEMERALONLOCALSESSION, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      KeeperException.AuthFailedException keeperException_AuthFailedException0 = new KeeperException.AuthFailedException();
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      KeeperException.UnknownSessionException keeperException_UnknownSessionException0 = new KeeperException.UnknownSessionException();
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      KeeperException.NodeExistsException keeperException_NodeExistsException0 = new KeeperException.NodeExistsException("XqSEkh{g&|iT#B");
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NODEEXISTS;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.NODEEXISTS, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONEXPIRED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0, "u6.{+k=caXhz*VWXP");
      assertEquals("u6.{+k=caXhz*VWXP", keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SYSTEMERROR;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      KeeperException.QuotaExceededException keeperException_QuotaExceededException0 = new KeeperException.QuotaExceededException("90\"-PNaK VkU`],v\"");
      String string0 = keeperException_QuotaExceededException0.getMessage();
      assertEquals("KeeperErrorCode = Quota has exceeded for 90\"-PNaK VkU`],v\"", string0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      KeeperException.QuotaExceededException keeperException_QuotaExceededException0 = new KeeperException.QuotaExceededException();
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.UNIMPLEMENTED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      String string0 = keeperException0.getMessage();
      assertEquals("KeeperErrorCode = Unimplemented", string0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.THROTTLEDOP;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-127), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.CONNECTIONLOSS;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-4), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOTEMPTY;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-111), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.APIERROR;
      KeeperException.APIErrorException keeperException_APIErrorException0 = (KeeperException.APIErrorException)KeeperException.create(keeperException_Code0);
      LinkedList<OpResult> linkedList0 = new LinkedList<OpResult>();
      LinkedList<Locale.LanguageRange> linkedList1 = new LinkedList<Locale.LanguageRange>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.EXTENDED_FILTERING;
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) linkedList1, (Collection<String>) null, locale_FilteringMode0);
      OpResult.GetChildrenResult opResult_GetChildrenResult0 = new OpResult.GetChildrenResult(list0);
      linkedList0.add((OpResult) opResult_GetChildrenResult0);
      keeperException_APIErrorException0.setMultiResults(linkedList0);
      List<OpResult> list1 = keeperException_APIErrorException0.getResults();
      assertEquals(1, list1.size());
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      KeeperException.BadArgumentsException keeperException_BadArgumentsException0 = new KeeperException.BadArgumentsException("R");
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.BADARGUMENTS;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-8), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      KeeperException.NoNodeException keeperException_NoNodeException0 = new KeeperException.NoNodeException("org.apache.zookeeper.OpResult$GetChildrenResult");
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NONODE;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-101), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOAUTH;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.NOAUTH, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      KeeperException.ReconfigDisabledException keeperException_ReconfigDisabledException0 = new KeeperException.ReconfigDisabledException("g");
      String string0 = keeperException_ReconfigDisabledException0.getMessage();
      assertEquals("KeeperErrorCode = Reconfig is disabled for g", string0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.RECONFIGDISABLED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-123), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.DATAINCONSISTENCY;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-3), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONCLOSEDREQUIRESASLAUTH;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.SESSIONCLOSEDREQUIRESASLAUTH, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      KeeperException.SessionClosedRequireAuthException keeperException_SessionClosedRequireAuthException0 = new KeeperException.SessionClosedRequireAuthException("#koNK}Z):.L'iqI(7[(");
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.RUNTIMEINCONSISTENCY;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOWATCHER;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.NOWATCHER, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      KeeperException.NoWatcherException keeperException_NoWatcherException0 = new KeeperException.NoWatcherException("Q1NU9 8Wr*7dpS");
      String string0 = keeperException_NoWatcherException0.getMessage();
      assertEquals("KeeperErrorCode = No such watcher for Q1NU9 8Wr*7dpS", string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.INVALIDACL;
      KeeperException.InvalidACLException keeperException_InvalidACLException0 = (KeeperException.InvalidACLException)KeeperException.create(keeperException_Code0);
      LinkedList<OpResult> linkedList0 = new LinkedList<OpResult>();
      keeperException_InvalidACLException0.setMultiResults(linkedList0);
      List<OpResult> list0 = keeperException_InvalidACLException0.getResults();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      KeeperException.InvalidACLException keeperException_InvalidACLException0 = new KeeperException.InvalidACLException("org.apache.zookeeper.OpResult");
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NEWCONFIGNOQUORUM;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.NEWCONFIGNOQUORUM, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.REQUESTTIMEOUT;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOTREADONLY;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-119), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      KeeperException.NoChildrenForEphemeralsException keeperException_NoChildrenForEphemeralsException0 = new KeeperException.NoChildrenForEphemeralsException();
      int int0 = keeperException_NoChildrenForEphemeralsException0.getCode();
      assertEquals((-108), int0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.create((KeeperException.Code) null, "KeeperErrorCode = Reconfig is disabled for g");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.create(5462);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The current client version cannot lookup this code:5462
         //
         verifyException("org.apache.zookeeper.KeeperException$Code", e);
      }
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.create((-981), "org.apache.zookeeper.OpResult$ErrorResult");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The current client version cannot lookup this code:-981
         //
         verifyException("org.apache.zookeeper.KeeperException$Code", e);
      }
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      KeeperException.NotEmptyException keeperException_NotEmptyException0 = new KeeperException.NotEmptyException("");
      KeeperException.Code keeperException_Code0 = keeperException_NotEmptyException0.code();
      assertEquals((-111), keeperException_Code0.intValue());
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      KeeperException.MarshallingErrorException keeperException_MarshallingErrorException0 = new KeeperException.MarshallingErrorException();
      // Undeclared exception!
      try { 
        keeperException_MarshallingErrorException0.setCode(764);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The current client version cannot lookup this code:764
         //
         verifyException("org.apache.zookeeper.KeeperException$Code", e);
      }
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      KeeperException.BadVersionException keeperException_BadVersionException0 = new KeeperException.BadVersionException("',1");
      String string0 = keeperException_BadVersionException0.getPath();
      assertEquals("',1", string0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.UNIMPLEMENTED;
      int int0 = keeperException_Code0.intValue();
      assertEquals((-6), int0);
  }
}
