/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 14 18:51:34 GMT 2026
 */

package org.apache.zookeeper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.apache.zookeeper.KeeperException;
import org.apache.zookeeper.OpResult;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class KeeperException_ESTest extends KeeperException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<OpResult> linkedList0 = new LinkedList<OpResult>();
      linkedList0.add((OpResult) null);
      KeeperException.BadVersionException keeperException_BadVersionException0 = new KeeperException.BadVersionException();
      keeperException_BadVersionException0.setMultiResults(linkedList0);
      List<OpResult> list0 = keeperException_BadVersionException0.getResults();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      KeeperException.NoNodeException keeperException_NoNodeException0 = new KeeperException.NoNodeException("k(*~");
      String string0 = keeperException_NoNodeException0.getPath();
      assertEquals("k(*~", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      KeeperException.SessionClosedRequireAuthException keeperException_SessionClosedRequireAuthException0 = new KeeperException.SessionClosedRequireAuthException("");
      String string0 = keeperException_SessionClosedRequireAuthException0.getPath();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.AUTHFAILED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0, "\"PPAvir6");
      assertEquals("\"PPAvir6", keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      KeeperException keeperException0 = KeeperException.create((-100), (String) null);
      assertEquals((-100), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      KeeperException.QuotaExceededException keeperException_QuotaExceededException0 = new KeeperException.QuotaExceededException("m");
      keeperException_QuotaExceededException0.setCode(0);
      KeeperException.Code keeperException_Code0 = keeperException_QuotaExceededException0.code();
      assertEquals(KeeperException.Code.OK, keeperException_Code0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.getCodeMessage((KeeperException.Code) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.create((KeeperException.Code) null, "x");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.create((KeeperException.Code) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.create(8);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The current client version cannot lookup this code:8
         //
         verifyException("org.apache.zookeeper.KeeperException$Code", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.get((-12));
      assertEquals(KeeperException.Code.UNKNOWNSESSION, keeperException_Code0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.Code.get(491);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The current client version cannot lookup this code:491
         //
         verifyException("org.apache.zookeeper.KeeperException$Code", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.REQUESTTIMEOUT;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.REQUESTTIMEOUT, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.UNKNOWNSESSION;
      // Undeclared exception!
      try { 
        KeeperException.create(keeperException_Code0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid exception code:-12
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      KeeperException.ThrottledOpException keeperException_ThrottledOpException0 = new KeeperException.ThrottledOpException();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      KeeperException.UnimplementedException keeperException_UnimplementedException0 = new KeeperException.UnimplementedException();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      KeeperException.ConnectionLossException keeperException_ConnectionLossException0 = new KeeperException.ConnectionLossException();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      KeeperException.NewConfigNoQuorum keeperException_NewConfigNoQuorum0 = new KeeperException.NewConfigNoQuorum();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      KeeperException.SessionExpiredException keeperException_SessionExpiredException0 = new KeeperException.SessionExpiredException();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      KeeperException.NoChildrenForEphemeralsException keeperException_NoChildrenForEphemeralsException0 = new KeeperException.NoChildrenForEphemeralsException();
      List<OpResult> list0 = keeperException_NoChildrenForEphemeralsException0.getResults();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.THROTTLEDOP;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Op throttled due to high load", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      KeeperException.RequestTimeoutException keeperException_RequestTimeoutException0 = new KeeperException.RequestTimeoutException();
      String string0 = keeperException_RequestTimeoutException0.getMessage();
      assertEquals("KeeperErrorCode = Unknown error REQUESTTIMEOUT", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      KeeperException.InvalidCallbackException keeperException_InvalidCallbackException0 = new KeeperException.InvalidCallbackException();
      String string0 = keeperException_InvalidCallbackException0.getMessage();
      assertEquals("KeeperErrorCode = Invalid callback", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONEXPIRED;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Session expired", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      KeeperException.ReconfigInProgress keeperException_ReconfigInProgress0 = new KeeperException.ReconfigInProgress();
      String string0 = keeperException_ReconfigInProgress0.getMessage();
      assertEquals("KeeperErrorCode = ReconfigInProgress", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NEWCONFIGNOQUORUM;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("NewConfigNoQuorum", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.UNIMPLEMENTED;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("Unimplemented", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.CONNECTIONLOSS;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("ConnectionLoss", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.OK;
      String string0 = KeeperException.getCodeMessage(keeperException_Code0);
      assertEquals("ok", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.QUOTAEXCEEDED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.QUOTAEXCEEDED, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONCLOSEDREQUIRESASLAUTH;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.RECONFIGDISABLED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.RECONFIGDISABLED, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOWATCHER;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.NOWATCHER, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.EPHEMERALONLOCALSESSION;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOTREADONLY;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.NOTREADONLY, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONMOVED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.AUTHFAILED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-115), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.INVALIDACL;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-114), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOTEMPTY;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-111), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NODEEXISTS;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-110), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOCHILDRENFOREPHEMERALS;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.NOCHILDRENFOREPHEMERALS, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.BADVERSION;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NOAUTH;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-102), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NONODE;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.NONODE, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.APIERROR;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.APIERROR, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.RECONFIGINPROGRESS;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-14), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.BADARGUMENTS;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.BADARGUMENTS, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.OPERATIONTIMEOUT;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.OPERATIONTIMEOUT, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.MARSHALLINGERROR;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.DATAINCONSISTENCY;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.RUNTIMEINCONSISTENCY;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals(KeeperException.Code.RUNTIMEINCONSISTENCY, keeperException0.code());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SYSTEMERROR;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.OK;
      // Undeclared exception!
      try { 
        KeeperException.create(keeperException_Code0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid exception code:0
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      KeeperException.OperationTimeoutException keeperException_OperationTimeoutException0 = new KeeperException.OperationTimeoutException();
      String string0 = keeperException_OperationTimeoutException0.getMessage();
      assertEquals("KeeperErrorCode = OperationTimeout", string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      KeeperException.BadVersionException keeperException_BadVersionException0 = new KeeperException.BadVersionException("HO1 ");
      String string0 = keeperException_BadVersionException0.getMessage();
      assertEquals("KeeperErrorCode = BadVersion for HO1 ", string0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      KeeperException.SessionMovedException keeperException_SessionMovedException0 = new KeeperException.SessionMovedException();
      String string0 = keeperException_SessionMovedException0.getMessage();
      assertEquals("KeeperErrorCode = Session moved", string0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      KeeperException.NoChildrenForEphemeralsException keeperException_NoChildrenForEphemeralsException0 = new KeeperException.NoChildrenForEphemeralsException();
      String string0 = keeperException_NoChildrenForEphemeralsException0.getMessage();
      assertEquals("KeeperErrorCode = NoChildrenForEphemerals", string0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      KeeperException.NoChildrenForEphemeralsException keeperException_NoChildrenForEphemeralsException0 = new KeeperException.NoChildrenForEphemeralsException("4}t/V>");
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.INVALIDCALLBACK;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      KeeperException.EphemeralOnLocalSessionException keeperException_EphemeralOnLocalSessionException0 = new KeeperException.EphemeralOnLocalSessionException();
      String string0 = keeperException_EphemeralOnLocalSessionException0.getMessage();
      assertEquals("KeeperErrorCode = Ephemeral node on local session", string0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      KeeperException.AuthFailedException keeperException_AuthFailedException0 = new KeeperException.AuthFailedException();
      String string0 = keeperException_AuthFailedException0.getMessage();
      assertEquals("KeeperErrorCode = AuthFailed", string0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      KeeperException.UnknownSessionException keeperException_UnknownSessionException0 = new KeeperException.UnknownSessionException();
      String string0 = keeperException_UnknownSessionException0.getMessage();
      assertEquals("KeeperErrorCode = Unknown error UNKNOWNSESSION", string0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      KeeperException.NodeExistsException keeperException_NodeExistsException0 = new KeeperException.NodeExistsException();
      String string0 = keeperException_NodeExistsException0.getMessage();
      assertEquals("KeeperErrorCode = NodeExists", string0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.SESSIONEXPIRED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      KeeperException.SystemErrorException keeperException_SystemErrorException0 = new KeeperException.SystemErrorException();
      String string0 = keeperException_SystemErrorException0.getMessage();
      assertEquals("KeeperErrorCode = SystemError", string0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      KeeperException.QuotaExceededException keeperException_QuotaExceededException0 = new KeeperException.QuotaExceededException();
      String string0 = keeperException_QuotaExceededException0.getMessage();
      assertEquals("KeeperErrorCode = Quota has exceeded", string0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      KeeperException.MarshallingErrorException keeperException_MarshallingErrorException0 = new KeeperException.MarshallingErrorException();
      String string0 = keeperException_MarshallingErrorException0.getMessage();
      assertEquals("KeeperErrorCode = MarshallingError", string0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.UNIMPLEMENTED;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-6), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.THROTTLEDOP;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-127), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.CONNECTIONLOSS;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertEquals((-4), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      KeeperException.NotEmptyException keeperException_NotEmptyException0 = new KeeperException.NotEmptyException("K|k%");
      String string0 = keeperException_NotEmptyException0.getMessage();
      assertEquals("KeeperErrorCode = Directory not empty for K|k%", string0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      KeeperException.NotEmptyException keeperException_NotEmptyException0 = new KeeperException.NotEmptyException();
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      KeeperException.APIErrorException keeperException_APIErrorException0 = new KeeperException.APIErrorException();
      String string0 = keeperException_APIErrorException0.getMessage();
      assertEquals("KeeperErrorCode = APIError", string0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      KeeperException.BadArgumentsException keeperException_BadArgumentsException0 = new KeeperException.BadArgumentsException();
      String string0 = keeperException_BadArgumentsException0.getMessage();
      assertEquals("KeeperErrorCode = BadArguments", string0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      KeeperException.NoNodeException keeperException_NoNodeException0 = new KeeperException.NoNodeException((String) null);
      String string0 = keeperException_NoNodeException0.getMessage();
      assertEquals("KeeperErrorCode = NoNode", string0);
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      KeeperException.NoAuthException keeperException_NoAuthException0 = new KeeperException.NoAuthException();
      String string0 = keeperException_NoAuthException0.getMessage();
      assertEquals("KeeperErrorCode = NoAuth", string0);
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      KeeperException.ReconfigDisabledException keeperException_ReconfigDisabledException0 = new KeeperException.ReconfigDisabledException("");
      String string0 = keeperException_ReconfigDisabledException0.getMessage();
      assertEquals("KeeperErrorCode = Reconfig is disabled", string0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      KeeperException.ReconfigDisabledException keeperException_ReconfigDisabledException0 = new KeeperException.ReconfigDisabledException();
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      KeeperException.DataInconsistencyException keeperException_DataInconsistencyException0 = new KeeperException.DataInconsistencyException();
      String string0 = keeperException_DataInconsistencyException0.getMessage();
      assertEquals("KeeperErrorCode = DataInconsistency", string0);
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      KeeperException.SessionClosedRequireAuthException keeperException_SessionClosedRequireAuthException0 = new KeeperException.SessionClosedRequireAuthException();
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      KeeperException.SessionClosedRequireAuthException keeperException_SessionClosedRequireAuthException0 = new KeeperException.SessionClosedRequireAuthException("org.apache.zookeeper.OpResult$CreateResult");
      String string0 = keeperException_SessionClosedRequireAuthException0.getMessage();
      assertEquals("KeeperErrorCode = Session closed because client failed to authenticate for org.apache.zookeeper.OpResult$CreateResult", string0);
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      KeeperException.RuntimeInconsistencyException keeperException_RuntimeInconsistencyException0 = new KeeperException.RuntimeInconsistencyException();
      String string0 = keeperException_RuntimeInconsistencyException0.getMessage();
      assertEquals("KeeperErrorCode = RuntimeInconsistency", string0);
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      KeeperException.NoWatcherException keeperException_NoWatcherException0 = new KeeperException.NoWatcherException();
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      KeeperException.NoWatcherException keeperException_NoWatcherException0 = new KeeperException.NoWatcherException((String) null);
      String string0 = keeperException_NoWatcherException0.getMessage();
      assertEquals("KeeperErrorCode = No such watcher", string0);
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      KeeperException.InvalidACLException keeperException_InvalidACLException0 = new KeeperException.InvalidACLException();
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      KeeperException.InvalidACLException keeperException_InvalidACLException0 = new KeeperException.InvalidACLException("nx");
      String string0 = keeperException_InvalidACLException0.getMessage();
      assertEquals("KeeperErrorCode = InvalidACL for nx", string0);
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NEWCONFIGNOQUORUM;
      KeeperException keeperException0 = KeeperException.create(keeperException_Code0);
      assertNull(keeperException0.getPath());
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
      KeeperException.NotReadOnlyException keeperException_NotReadOnlyException0 = new KeeperException.NotReadOnlyException();
      String string0 = keeperException_NotReadOnlyException0.getMessage();
      assertEquals("KeeperErrorCode = Not a read-only call", string0);
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      KeeperException.BadArgumentsException keeperException_BadArgumentsException0 = new KeeperException.BadArgumentsException("NOTREADONLY");
      int int0 = keeperException_BadArgumentsException0.getCode();
      assertEquals((-8), int0);
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      KeeperException.RequestTimeoutException keeperException_RequestTimeoutException0 = new KeeperException.RequestTimeoutException();
      LinkedList<OpResult> linkedList0 = new LinkedList<OpResult>();
      keeperException_RequestTimeoutException0.setMultiResults(linkedList0);
      List<OpResult> list0 = keeperException_RequestTimeoutException0.getResults();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.UNKNOWNSESSION;
      // Undeclared exception!
      try { 
        KeeperException.create(keeperException_Code0, "org.apache.zookeeper.OpResult$CheckResult");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid exception code:-12
         //
         verifyException("org.apache.zookeeper.KeeperException", e);
      }
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      KeeperException keeperException0 = KeeperException.create((-122));
      assertEquals((-122), keeperException0.getCode());
  }

  @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      // Undeclared exception!
      try { 
        KeeperException.create(24, "org.apache.zookeeper.OpResult$ErrorResult");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The current client version cannot lookup this code:24
         //
         verifyException("org.apache.zookeeper.KeeperException$Code", e);
      }
  }

  @Test(timeout = 4000)
  public void test93()  throws Throwable  {
      KeeperException.NoNodeException keeperException_NoNodeException0 = new KeeperException.NoNodeException();
      KeeperException.Code keeperException_Code0 = keeperException_NoNodeException0.code();
      assertEquals((-101), keeperException_Code0.intValue());
  }

  @Test(timeout = 4000)
  public void test94()  throws Throwable  {
      KeeperException.ReconfigInProgress keeperException_ReconfigInProgress0 = new KeeperException.ReconfigInProgress();
      // Undeclared exception!
      try { 
        keeperException_ReconfigInProgress0.setCode((-1340));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The current client version cannot lookup this code:-1340
         //
         verifyException("org.apache.zookeeper.KeeperException$Code", e);
      }
  }

  @Test(timeout = 4000)
  public void test95()  throws Throwable  {
      KeeperException.NodeExistsException keeperException_NodeExistsException0 = new KeeperException.NodeExistsException((String) null);
      String string0 = keeperException_NodeExistsException0.getPath();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test96()  throws Throwable  {
      KeeperException.Code keeperException_Code0 = KeeperException.Code.NONODE;
      int int0 = keeperException_Code0.intValue();
      assertEquals((-101), int0);
  }
}
