/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 14 18:47:44 GMT 2026
 */

package org.apache.zookeeper.server.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.DataInputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import java.util.Map;
import org.apache.zookeeper.server.admin.CommandResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResponse_ESTest extends CommandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PipedInputStream pipedInputStream0 = new PipedInputStream(pipedOutputStream0);
      CommandResponse commandResponse0 = new CommandResponse("", "", (-404), pipedInputStream0);
      commandResponse0.put("", "");
      commandResponse0.put("", "");
      assertEquals((-404), commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
      assertEquals("", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, "`UTgK", 422);
      commandResponse0.setStatusCode(0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("command", "command", (-4330));
      int int0 = commandResponse0.getStatusCode();
      assertEquals("command", commandResponse0.getCommand());
      assertEquals((-4330), int0);
      assertEquals("command", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("*_Ge{)W y9AV9", "*_Ge{)W y9AV9", 4327);
      Enumeration<DataInputStream> enumeration0 = (Enumeration<DataInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      commandResponse0.setInputStream(sequenceInputStream0);
      commandResponse0.getInputStream();
      assertEquals("*_Ge{)W y9AV9", commandResponse0.getCommand());
      assertEquals(4327, commandResponse0.getStatusCode());
      assertEquals("*_Ge{)W y9AV9", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, (-4330));
      String string0 = commandResponse0.getError();
      assertNull(string0);
      assertEquals((-4330), commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PipedInputStream pipedInputStream0 = new PipedInputStream(pipedOutputStream0);
      CommandResponse commandResponse0 = new CommandResponse("", "", (-404), pipedInputStream0);
      String string0 = commandResponse0.getError();
      assertEquals("", string0);
      assertEquals((-404), commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, "@<", 200);
      String string0 = commandResponse0.getCommand();
      assertEquals(200, commandResponse0.getStatusCode());
      assertNull(string0);
      assertEquals("@<", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PipedInputStream pipedInputStream0 = new PipedInputStream(pipedOutputStream0);
      CommandResponse commandResponse0 = new CommandResponse("", "", (-404), pipedInputStream0);
      String string0 = commandResponse0.getCommand();
      assertEquals("", string0);
      assertEquals("", commandResponse0.getError());
      assertEquals((-404), commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("4c,3iOxu");
      // Undeclared exception!
      try { 
        commandResponse0.putAll((Map<String, ?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("*_Ge{)W y9AV9", "*_Ge{)W y9AV9", 4327);
      String string0 = commandResponse0.getError();
      assertEquals(4327, commandResponse0.getStatusCode());
      assertEquals("*_Ge{)W y9AV9", commandResponse0.getCommand());
      assertEquals("*_Ge{)W y9AV9", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("*_Ge{)W y9AV9", "*_Ge{)W y9AV9", 4327);
      commandResponse0.addHeader("%`?1ju", "*_Ge{)W y9AV9");
      commandResponse0.getHeaders();
      assertEquals("*_Ge{)W y9AV9", commandResponse0.getError());
      assertEquals(4327, commandResponse0.getStatusCode());
      assertEquals("*_Ge{)W y9AV9", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, "`UTgK", 422);
      int int0 = commandResponse0.getStatusCode();
      assertEquals("`UTgK", commandResponse0.getError());
      assertEquals(422, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("*_Ge{)W y9AV9", "*_Ge{)W y9AV9", 4327);
      Map<String, String> map0 = commandResponse0.getHeaders();
      commandResponse0.putAll(map0);
      assertEquals(4327, commandResponse0.getStatusCode());
      assertEquals("*_Ge{)W y9AV9", commandResponse0.getError());
      assertEquals("*_Ge{)W y9AV9", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.toMap();
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("*_Ge{)W y9AV9", "*_Ge{)W y9AV9", 4327);
      commandResponse0.getInputStream();
      assertEquals(4327, commandResponse0.getStatusCode());
      assertEquals("*_Ge{)W y9AV9", commandResponse0.getError());
      assertEquals("*_Ge{)W y9AV9", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("error", "error", (-406));
      String string0 = commandResponse0.getCommand();
      assertEquals("error", commandResponse0.getError());
      assertEquals((-406), commandResponse0.getStatusCode());
      assertEquals("error", string0);
  }
}
