/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 14 19:02:15 GMT 2026
 */

package org.apache.zookeeper.server.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.util.Map;
import org.apache.zookeeper.server.admin.CommandResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResponse_ESTest extends CommandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, (-847), (-847));
      CommandResponse commandResponse0 = new CommandResponse("Vs`;)bEKDF", "Vs`;)bEKDF", 0, byteArrayInputStream0);
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("Vs`;)bEKDF", commandResponse0.getError());
      assertEquals("Vs`;)bEKDF", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.setStatusCode(0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.setStatusCode((-1));
      int int0 = commandResponse0.getStatusCode();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "RxjS8GE7=0Zf&7Ob", 0);
      byte[] byteArray0 = new byte[1];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, 1, 0);
      commandResponse0.setInputStream(byteArrayInputStream0);
      commandResponse0.getInputStream();
      assertEquals("RxjS8GE7=0Zf&7Ob", commandResponse0.getError());
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "command", (-2934));
      String string0 = commandResponse0.getError();
      assertEquals("command", string0);
      assertEquals("", commandResponse0.getCommand());
      assertEquals((-2934), commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 705);
      String string0 = commandResponse0.getError();
      assertEquals("", string0);
      assertEquals("", commandResponse0.getCommand());
      assertEquals(705, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("<t&BS2v<;1Chz_/!6.");
      String string0 = commandResponse0.getCommand();
      assertEquals("<t&BS2v<;1Chz_/!6.", string0);
      assertEquals(200, commandResponse0.getStatusCode());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "RxjS8GE7=0Zf&7Ob", 0);
      String string0 = commandResponse0.getCommand();
      assertEquals("RxjS8GE7=0Zf&7Ob", commandResponse0.getError());
      assertEquals("", string0);
      assertEquals(0, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("e3H");
      // Undeclared exception!
      try { 
        commandResponse0.putAll((Map<String, ?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      String string0 = commandResponse0.getError();
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.put("", "c;xLpAr1Ho");
      commandResponse0.put("", "--X9RxWua");
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.addHeader("", "[]J*W%dj=$6}c`'");
      commandResponse0.getHeaders();
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      int int0 = commandResponse0.getStatusCode();
      assertEquals("", commandResponse0.getCommand());
      assertEquals(200, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.getHeaders();
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      Map<String, Object> map0 = commandResponse0.toMap();
      commandResponse0.putAll(map0);
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.getInputStream();
      assertEquals("", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      String string0 = commandResponse0.getCommand();
      assertEquals(200, commandResponse0.getStatusCode());
      assertNull(string0);
  }
}
