/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 14 18:53:31 GMT 2026
 */

package org.apache.zookeeper.server.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.DataInputStream;
import java.io.InputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import java.util.Map;
import org.apache.zookeeper.server.admin.CommandResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResponse_ESTest extends CommandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "y 5$a/", 839);
      commandResponse0.put("", "y 5$a/");
      commandResponse0.put("", (Object) null);
      assertEquals(839, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
      assertEquals("y 5$a/", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.setStatusCode(0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(200, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 1952);
      Enumeration<SequenceInputStream> enumeration0 = (Enumeration<SequenceInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      commandResponse0.setInputStream(sequenceInputStream0);
      commandResponse0.getInputStream();
      assertEquals(1952, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.addHeader("%naq", "");
      commandResponse0.getHeaders();
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "y 5$a/", 839);
      String string0 = commandResponse0.getError();
      assertEquals("", commandResponse0.getCommand());
      assertEquals(839, commandResponse0.getStatusCode());
      assertEquals("y 5$a/", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("KvEbF20$0gJY,Rz", "", 1);
      String string0 = commandResponse0.getError();
      assertEquals("KvEbF20$0gJY,Rz", commandResponse0.getCommand());
      assertEquals("", string0);
      assertEquals(1, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 1952);
      String string0 = commandResponse0.getCommand();
      assertEquals(1952, commandResponse0.getStatusCode());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", (String) null, (-1121));
      String string0 = commandResponse0.getCommand();
      assertEquals((-1121), commandResponse0.getStatusCode());
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("Jg}");
      // Undeclared exception!
      try { 
        commandResponse0.putAll((Map<String, ?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      String string0 = commandResponse0.getError();
      assertEquals(200, commandResponse0.getStatusCode());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DataInputStream dataInputStream0 = new DataInputStream((InputStream) null);
      CommandResponse commandResponse0 = new CommandResponse("v}W", "", (-849), dataInputStream0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals("v}W", commandResponse0.getCommand());
      assertEquals((-849), int0);
      assertEquals("", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      Map<String, String> map0 = commandResponse0.getHeaders();
      commandResponse0.putAll(map0);
      assertEquals("", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("_FwI`T\"V0ZOWU7T");
      commandResponse0.getInputStream();
      assertEquals("_FwI`T\"V0ZOWU7T", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("_FwI`T\"V0ZOWU7T");
      String string0 = commandResponse0.getCommand();
      assertEquals("_FwI`T\"V0ZOWU7T", string0);
      assertNotNull(string0);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.toMap();
      assertEquals("", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }
}
