/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 13 17:58:57 GMT 2026
 */

package org.apache.zookeeper.server.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.PushbackInputStream;
import java.util.Map;
import org.apache.zookeeper.server.admin.CommandResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResponse_ESTest extends CommandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      Map<String, String> map0 = commandResponse0.getHeaders();
      commandResponse0.addHeader("", "");
      commandResponse0.putAll(map0);
      Object object0 = commandResponse0.put("", (Object) null);
      assertEquals("", object0);
      assertEquals(200, commandResponse0.getStatusCode());
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.setStatusCode(0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", (-1073));
      int int0 = commandResponse0.getStatusCode();
      assertEquals("", commandResponse0.getError());
      assertEquals((-1073), int0);
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      PushbackInputStream pushbackInputStream0 = new PushbackInputStream(byteArrayInputStream0, 224);
      CommandResponse commandResponse0 = new CommandResponse("", "e1wlj\"", (-1), pushbackInputStream0);
      commandResponse0.getInputStream();
      assertEquals("", commandResponse0.getCommand());
      assertEquals((-1), commandResponse0.getStatusCode());
      assertEquals("e1wlj\"", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("nQJQ )ijW#4f", "nQJQ )ijW#4f", (-1923));
      String string0 = commandResponse0.getError();
      assertEquals("nQJQ )ijW#4f", commandResponse0.getCommand());
      assertEquals((-1923), commandResponse0.getStatusCode());
      assertEquals("nQJQ )ijW#4f", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 3193, (InputStream) null);
      String string0 = commandResponse0.getError();
      assertEquals(3193, commandResponse0.getStatusCode());
      assertEquals("", string0);
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      String string0 = commandResponse0.getCommand();
      assertNull(string0);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("5jU `lv:Tt");
      String string0 = commandResponse0.getCommand();
      assertNotNull(string0);
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("5jU `lv:Tt", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      // Undeclared exception!
      try { 
        commandResponse0.putAll((Map<String, ?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      String string0 = commandResponse0.getError();
      assertNull(string0);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.put("5", (Object) null);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.addHeader((String) null, "");
      commandResponse0.getHeaders();
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(200, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.setInputStream((InputStream) null);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.toMap();
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.getInputStream();
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      String string0 = commandResponse0.getCommand();
      assertEquals(200, commandResponse0.getStatusCode());
      assertNotNull(string0);
      assertEquals("", string0);
  }
}
