/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 13 17:01:21 GMT 2026
 */

package org.apache.zookeeper.test.evosuite.c1.commandresponse;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.PipedInputStream;
import java.util.Map;
import org.apache.zookeeper.server.admin.CommandResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResponse_ESTest extends CommandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      commandResponse0.put("e%VN`5TfJ,H#o=zE", "s%pQv9t&->99A+");
      commandResponse0.put("e%VN`5TfJ,H#o=zE", "e%VN`5TfJ,H#o=zE");
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      CommandResponse commandResponse0 = new CommandResponse("", "", 0, pipedInputStream0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals("", commandResponse0.getError());
      assertEquals("", commandResponse0.getCommand());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("WJ", "WJ", (-1));
      int int0 = commandResponse0.getStatusCode();
      assertEquals((-1), int0);
      assertEquals("WJ", commandResponse0.getCommand());
      assertEquals("WJ", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("org.apache.zookeeper.server.admin.CommandResponse");
      commandResponse0.getInputStream();
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("org.apache.zookeeper.server.admin.CommandResponse", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("org.apache.zookeeper.server.admin.CommandResponse");
      commandResponse0.addHeader("command", "");
      commandResponse0.getHeaders();
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("org.apache.zookeeper.server.admin.CommandResponse", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      CommandResponse commandResponse0 = new CommandResponse("", ">h", 0, pipedInputStream0);
      String string0 = commandResponse0.getError();
      assertEquals(">h", string0);
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("WJ", "WJ", (-1));
      String string0 = commandResponse0.getCommand();
      assertEquals("WJ", string0);
      assertEquals("WJ", commandResponse0.getError());
      assertEquals((-1), commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      CommandResponse commandResponse0 = new CommandResponse("", "", 0, pipedInputStream0);
      String string0 = commandResponse0.getCommand();
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getError());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("|~WC9fdtctXa");
      // Undeclared exception!
      try { 
        commandResponse0.putAll((Map<String, ?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      CommandResponse commandResponse0 = new CommandResponse("", "", 0, pipedInputStream0);
      String string0 = commandResponse0.getError();
      assertEquals("", commandResponse0.getCommand());
      assertEquals("", string0);
      assertEquals(0, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(200, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      Map<String, String> map0 = commandResponse0.getHeaders();
      commandResponse0.putAll(map0);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      commandResponse0.setInputStream(pipedInputStream0);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.toMap();
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      CommandResponse commandResponse0 = new CommandResponse("", "", 0, pipedInputStream0);
      commandResponse0.getInputStream();
      assertEquals("", commandResponse0.getCommand());
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      CommandResponse commandResponse0 = new CommandResponse("", "", 0, pipedInputStream0);
      commandResponse0.setStatusCode(0);
      assertEquals("", commandResponse0.getError());
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      String string0 = commandResponse0.getCommand();
      assertNull(string0);
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("");
      String string0 = commandResponse0.getError();
      assertEquals(200, commandResponse0.getStatusCode());
      assertNull(string0);
      assertEquals("", commandResponse0.getCommand());
  }
}
