/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 13 16:14:54 GMT 2026
 */

package org.apache.zookeeper.test.evosuite.c0.commandresponse;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.PushbackInputStream;
import java.util.Map;
import org.apache.zookeeper.server.admin.CommandResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResponse_ESTest extends CommandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("=d@iv4/}f.tAHA", "=d@iv4/}f.tAHA", 490);
      commandResponse0.addHeader("=d@iv4/}f.tAHA", (String) null);
      assertEquals("=d@iv4/}f.tAHA", commandResponse0.getError());
      assertEquals(490, commandResponse0.getStatusCode());
      assertEquals("=d@iv4/}f.tAHA", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("=d@iv4/}f.tAHA", "=d@iv4/}f.tAHA", 490);
      commandResponse0.put("=d@iv4/}f.tAHA", "=d@iv4/}f.tAHA");
      commandResponse0.put("=d@iv4/}f.tAHA", (Object) null);
      assertEquals(490, commandResponse0.getStatusCode());
      assertEquals("=d@iv4/}f.tAHA", commandResponse0.getCommand());
      assertEquals("=d@iv4/}f.tAHA", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      CommandResponse commandResponse0 = new CommandResponse((String) null, "/<Lt?9~", 0, byteArrayInputStream0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals("/<Lt?9~", commandResponse0.getError());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.setStatusCode((-2926));
      int int0 = commandResponse0.getStatusCode();
      assertEquals((-2926), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("E8IF% 7");
      commandResponse0.addHeader("error", "error");
      commandResponse0.getHeaders();
      assertEquals("E8IF% 7", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("5YF");
      String string0 = commandResponse0.getError();
      assertEquals(200, commandResponse0.getStatusCode());
      assertNull(string0);
      assertEquals("5YF", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("=d@iv4/}f.tAHA", "=d@iv4/}f.tAHA", 490);
      String string0 = commandResponse0.getError();
      assertEquals(490, commandResponse0.getStatusCode());
      assertEquals("=d@iv4/}f.tAHA", commandResponse0.getCommand());
      assertEquals("=d@iv4/}f.tAHA", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("=d@iv4/}f.tAHA", "=d@iv4/}f.tAHA", 490);
      String string0 = commandResponse0.getCommand();
      assertEquals("=d@iv4/}f.tAHA", commandResponse0.getError());
      assertEquals("=d@iv4/}f.tAHA", string0);
      assertEquals(490, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 1422);
      String string0 = commandResponse0.getCommand();
      assertEquals("", commandResponse0.getError());
      assertEquals(1422, commandResponse0.getStatusCode());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("qZn3t");
      // Undeclared exception!
      try { 
        commandResponse0.putAll((Map<? extends String, ?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 1422);
      String string0 = commandResponse0.getError();
      assertEquals(1422, commandResponse0.getStatusCode());
      assertEquals("", string0);
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 1422);
      int int0 = commandResponse0.getStatusCode();
      assertEquals("", commandResponse0.getError());
      assertEquals(1422, int0);
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("+A#b");
      Map<String, String> map0 = commandResponse0.getHeaders();
      commandResponse0.putAll(map0);
      assertEquals("+A#b", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 1422);
      byte[] byteArray0 = new byte[2];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      PushbackInputStream pushbackInputStream0 = new PushbackInputStream(byteArrayInputStream0, 4312);
      DataInputStream dataInputStream0 = new DataInputStream(pushbackInputStream0);
      commandResponse0.setInputStream(dataInputStream0);
      commandResponse0.getInputStream();
      assertEquals("", commandResponse0.getCommand());
      assertEquals(1422, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getError());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.toMap();
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      commandResponse0.getInputStream();
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      String string0 = commandResponse0.getCommand();
      assertEquals(200, commandResponse0.getStatusCode());
      assertNull(string0);
  }
}
