/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 14 18:40:51 GMT 2026
 */

package org.apache.zookeeper.server.admin;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.PipedInputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import org.apache.zookeeper.server.admin.CommandResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommandResponse_ESTest extends CommandResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Enumeration<MockFileInputStream> enumeration0 = (Enumeration<MockFileInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      CommandResponse commandResponse0 = new CommandResponse("", "", 0, sequenceInputStream0);
      assertEquals("", commandResponse0.getError());
      assertEquals(0, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 0);
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      commandResponse0.putAll(hashMap0);
      assertEquals(0, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 1824);
      commandResponse0.put("", "");
      commandResponse0.put("", "");
      assertEquals("", commandResponse0.getError());
      assertEquals(1824, commandResponse0.getStatusCode());
      assertEquals("", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 0);
      int int0 = commandResponse0.getStatusCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("^-q'eysu$GZGRUu}", "/0OIzT]1F<", (-1));
      int int0 = commandResponse0.getStatusCode();
      assertEquals("/0OIzT]1F<", commandResponse0.getError());
      assertEquals((-1), int0);
      assertEquals("^-q'eysu$GZGRUu}", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 0);
      commandResponse0.addHeader("", "");
      commandResponse0.getHeaders();
      assertEquals(0, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("1=-+R,jlK&`8WsOX");
      String string0 = commandResponse0.getError();
      assertEquals("1=-+R,jlK&`8WsOX", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 1524);
      String string0 = commandResponse0.getError();
      assertEquals("", commandResponse0.getCommand());
      assertEquals("", string0);
      assertEquals(1524, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null, (String) null, 0);
      String string0 = commandResponse0.getCommand();
      assertNull(string0);
      assertEquals(0, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("'h5*46D", "'h5*46D", (-1));
      String string0 = commandResponse0.getCommand();
      assertEquals("'h5*46D", commandResponse0.getError());
      assertEquals((-1), commandResponse0.getStatusCode());
      assertEquals("'h5*46D", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("^-q'eysu$GZGRUu}", "/0OIzT]1F<", (-1));
      String string0 = commandResponse0.getError();
      assertEquals("^-q'eysu$GZGRUu}", commandResponse0.getCommand());
      assertEquals((-1), commandResponse0.getStatusCode());
      assertEquals("/0OIzT]1F<", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 1524);
      commandResponse0.addHeader("", ":.1_l-z\nkrr?c-a~");
      assertEquals("", commandResponse0.getError());
      assertEquals("", commandResponse0.getCommand());
      assertEquals(1524, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("qcrs,=1Z'pW%S");
      int int0 = commandResponse0.getStatusCode();
      assertEquals("qcrs,=1Z'pW%S", commandResponse0.getCommand());
      assertEquals(200, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("qcrs,=1ZpW%S");
      commandResponse0.getHeaders();
      assertEquals(200, commandResponse0.getStatusCode());
      assertEquals("qcrs,=1ZpW%S", commandResponse0.getCommand());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse((String) null);
      // Undeclared exception!
      try { 
        commandResponse0.putAll((Map<? extends String, ?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("^-q'eysu$GZGRUu}", "/0OIzT]1F<", (-1));
      PipedInputStream pipedInputStream0 = new PipedInputStream(1);
      commandResponse0.setInputStream(pipedInputStream0);
      commandResponse0.getInputStream();
      assertEquals("^-q'eysu$GZGRUu}", commandResponse0.getCommand());
      assertEquals("/0OIzT]1F<", commandResponse0.getError());
      assertEquals((-1), commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("qcrs,=1Z'pW%S");
      commandResponse0.toMap();
      assertEquals("qcrs,=1Z'pW%S", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("qcrs,=1Z'pW%S");
      commandResponse0.getInputStream();
      assertEquals("qcrs,=1Z'pW%S", commandResponse0.getCommand());
      assertEquals(200, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("qcrs,=1ZpW%S");
      commandResponse0.setStatusCode(0);
      assertEquals(0, commandResponse0.getStatusCode());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CommandResponse commandResponse0 = new CommandResponse("", "", 1524);
      String string0 = commandResponse0.getCommand();
      assertEquals("", commandResponse0.getError());
      assertEquals(1524, commandResponse0.getStatusCode());
      assertEquals("", string0);
  }
}
